all:
  is_secure: on
  credentials: SNSMember

registerInput:
  credentials: [[SNSRegisterBegin, SNSRegisterFinish]]

configComplete:
  is_secure: off

changeLanguage:
  is_secure: off

registerMobileToRegisterEnd:
  credentials: SNSRegisterFinish

registerMobileToRegisterEndFinish:
  credentials: SNSRegisterFinish
